#!/usr/bin/env bash

HOST_INSTALL_TMPFS="${HOST_INSTALL_TMPFS:-true}"
HOST_DISABLE_ROOT_SSH="${HOST_DISABLE_ROOT_SSH:-true}"
HOST_CONFIGURE_UFW="${HOST_CONFIGURE_UFW:-true}"
HOST_INSTALL_DOCKER="${HOST_INSTALL_DOCKER:-true}"
HOST_INSTALL_MONITORING_TOOLS="${HOST_INSTALL_MONITORING_TOOLS:-true}"
HOST_CREATE_DIRS="${HOST_CREATE_DIRS:-true}"
HOST_CREATE_HUSHLOGIN="${HOST_CREATE_HUSHLOGIN:-true}"
